### ISSUE TITLE
heroku auth:token fails: unexpected flag

### ISSUE THREAD

**Issue by jelko** [etianen/django-herokuapp#36]
`heroku auth:token` inside the init of `HerokuCommand` fails.

Some debugging shows that the command actually runs `/usr/local/bin/heroku auth:token --app=APP_NAME`. Heroku response is ` ▸    Unexpected flag: --app=APP_NAME` hence the command (and therefore the entire heroku_audit) is failing.

**Comment by etianen** [comment]
Huh, looks like they changed the behaviour of their client cli.

I've pushed up a fix to master.
